set-option -ga terminal-overrides ",alacritty,foot*,xterm-256color:Tc"
set -as terminal-features 'alacritty:rgb'
set -as terminal-features 'foot:rgb'
set -as terminal-features 'foot-extra:rgb'
set -g allow-rename off
set -g automatic-rename off
set -g mouse on
set-window-option -g aggressive-resize

bind-key = select-layout even-horizontal
bind-key \\ select-layout even-vertical
bind-key c run-shell "tnw"
bind-key ! run-shell "tnbp"
bind-key j command-prompt -p "join pane from:"  "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:"  "join-pane -t '%%'"
bind-key X set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

# --- Gruvbox Appearance Settings ---

# MAIN STATUS BAR
set -g status-style "fg=colour245,bg=colour235"
set -g status-interval 1

# LEFT SIDE (Session + Pane Title)
set -g status-left-length 80
set -g status-left "#[fg=colour235,bg=colour142,bold] #S #[default]#[bg=#fe8019,fg=colour235,bold] #{pane_title} #[default]"

# RIGHT SIDE (Host, Date, Time)
set -g status-right-length 60
set -g status-right "#[fg=colour109,bold] #H #[default]#[fg=colour245] | %d %b %Y #[default]#[fg=colour214,bold] | %H:%M #[default]"

# WINDOW LIST (numbers only)
set -g status-justify left
set -g window-status-format "#[fg=colour255,bg=colour235] #I #[default]"
set -g window-status-current-format "#[fg=colour235,bg=#8ec07c,bold] #I #[default]"
set -g window-status-separator " "

# PANES
set -g pane-border-style "fg=colour240"
set -g pane-active-border-style "fg=colour214"

# COMMAND/MESSAGE LINE
set -g message-style "fg=colour235,bg=colour214,bold"

# CLOCK
set -g clock-mode-colour colour109

# No destroy
set -g detach-on-destroy off
set -g exit-empty off
